### ISSUE TITLE
add community social media in the header

### ISSUE THREAD

**Issue by MichalPorag** [urish/pull-request-community#62]
Telegram: https://t.me/joinchat/SNHcwLegH2-Pjx4B
Facebook: https://www.facebook.com/groups/PullRequest
Discord: https://discord.gg/FDXyR4KP
Newsletter: https://forms.gle/cc6tSYQQEGnsbeAb9

![image](https://user-images.githubusercontent.com/47606575/108412207-3e0e7c00-7232-11eb-848f-6ad08f752695.png)

**Comment by soferdani** [comment]
can you please explain where to add this ?

**Comment by MichalPorag** [comment]
In the header. I had a image of the location.

**Comment by soferdani** [comment]
I mean - what is the name of the component where I can find this?  I tried in the layout folder it's not there I think

**Comment by lurx** [comment]
I'll take it.

**Comment by MichalPorag** [comment]
Thanks @lurx  great job!
