### ISSUE TITLE
Add a short description of the community and its goals to the top of the main page

### ISSUE THREAD

**Issue by urish** [urish/pull-request-community#65]
Something along the lines of: 

> Pull Request עוזרת לכם להיכנס לפרוייקטי קוד פתוח ולתרום להם ע"י יצירת סביבה תומכת ובטוחה וחיבור עם מנטורים בעלי ניסיון שאכפת להם שתצליחו.

**Comment by lurx** [comment]
Where exactly do you want this? between the navbar and the main content?

**Comment by urish** [comment]
Yes, it sounds like a good place

**Comment by MichalPorag** [comment]
@lurx 
The design is ready! do you want to take it?

**Comment by MichalPorag** [comment]
Replace the "לורם איפו...:" with:

״מוזמנים לתרום לפרויקט של הקהילה או לפרויקטים שרצים תחתיה בסדנאות שרצות אחת לחודש לתרומה לקוד פתוח. בנוסף מוזמנים להצטרף להרצאות העשרה, לשתף שאלות ובקשות לעזרה ולתף מהידע שלכם בקבוצה שלנו בפייסבוק.
אם אתם רוצים להיות מנטורים על פרויקט נשמח אם תיצרו קשר עם אחד ממנהלי הקהילה בפרטי.״

Link to Figma: https://www.figma.com/file/R4hJBfn1ghnKjTV73j0shr/Pull_Req?node-id=0%3A1

![image](https://user-images.githubusercontent.com/47606575/110372848-777b2000-8057-11eb-824b-6fc7c0058a73.png)

**Comment by NisanAyash** [comment]
@MichalPorag  
Hey, 
This is the issue, Please send me the details..

**Comment by NisanAyash** [comment]
Hey @MichalPorag ,
I'll be happy to help with this issue.
