### ISSUE TITLE
Adding ISSUE_TEMPLATE/

### ISSUE THREAD

**Issue by avivnakar** [urish/pull-request-community#68]
Offered issue templates can improve communication with community and also look pretty dope. Take a look at linuxserver.io's logo and structure on this issue template:
https://github.com/linuxserver/docker-code-server/issues/new?assignees=&labels=&template=issue.feature.md

Good templates can be:
- bug fix
- feature request
  - site related
  - code/repository related
- security issue

**Comment by urish** [comment]
I don't think we're facing any issue with the way people open issues right now, so I'd say this is a low priority. But feel free to prove me wrong :)

**Comment by avivnakar** [comment]
I agree, it probably is a low priority.

The idea is mainly to help new people to make their first issues with the suggested template, rather than being a rigid template to stick with in order to get any attention (as other projects might require)

Issuing should still be possible if you choose to avoid using any template.

**Comment by urish** [comment]
Closing for now as it's low priority
