### ISSUE TITLE
Add custom profile image support

### ISSUE THREAD

**Issue by urish** [urish/pull-request-community#78]
The README says:

```
2. By default, we'll use your GitHub photo. If you don't have a GitHub profile photo,
   or want to use a different one, add it under [public/images/people](public/images/people) in jpeg format.
   Use your GitHub username for the image, e.g. `MichalPorag.jpg`.

   Then, add `"customImage": true` to your profile JSON that you created in the previous step.
```

However, this is not implemented and currently confusing people (e.g. @strayblues), so I removed it from the README for now. But I think it's still useful, as some people don't have a GitHub profile photo and would still like to have their photo on the site.

**Comment by baruchiro** [comment]
Consider support [Gravatar](https://gravatar.com/)

**Comment by urish** [comment]
> Consider support Gravatar

Thanks for the suggestion! For gravatar to work, we'd need to have the email address of the user. I don't think most people would be comfortable sharing their personal email address publicly on GitHub

**Comment by baruchiro** [comment]
You can keep it optional... In anyway people sharing their media profiles...

**Comment by EladTal14** [comment]
plzzz assian me to this I'm the best

**Comment by urish** [comment]
@EladTal14 mind also adding the description back to the README?

```
2. By default, we'll use your GitHub photo. If you don't have a GitHub profile photo,
   or want to use a different one, add it under [public/images/people](public/images/people) in jpeg format.
   Use your GitHub username for the image, e.g. `MichalPorag.jpg`.

   Then, add `"customImage": true` to your profile JSON that you created in the previous step.
```

**Comment by EladTal14** [comment]
> @EladTal14 mind also adding the description back to the README?
> 
> ```
> 2. By default, we'll use your GitHub photo. If you don't have a GitHub profile photo,
>    or want to use a different one, add it under [public/images/people](public/images/people) in jpeg format.
>    Use your GitHub username for the image, e.g. `MichalPorag.jpg`.
> 
>    Then, add `"customImage": true` to your profile JSON that you created in the previous step.
> ```

It would be my pleasure.
