### ISSUE TITLE
Fix members grid CSS

### ISSUE THREAD

**Issue by MichalPorag** [urish/pull-request-community#93]
Right now, when open a "read more" in member card, the specific card is getting bigger but the other card in the line stay in the same size. 
The goal of this issue, is that all the line will increase the height according to the open card.

Tip: you can get this result with CSS grid.

![image](https://user-images.githubusercontent.com/47606575/111037192-c47e3e00-842b-11eb-8915-97da9e129a69.png)

**Comment by idomand** [comment]
Hi, I would like to resolve this issue.
